### ISSUE TITLE
Experience and Education section Date Mismatch

### ISSUE THREAD

**Issue by aswinzz** [NJACKWinterOfCode/LucidCV#18]
When first experience is added it shows DD-MM-YYYY but when more expeirences are added YYYY is only taken. Same for Education too.
![capture](https://user-images.githubusercontent.com/25057819/50229559-9f2b3280-03d0-11e9-8305-21bd68cd1b3b.PNG)

**Comment by tmsreekanth98** [comment]
Working on this.
