### ISSUE TITLE
Integrate newly added themes to the website

### ISSUE THREAD

**Issue by aswinzz** [NJACKWinterOfCode/LucidCV#3]
after creating the templates. they must be added to the form and according to the selection.
For that edit index.ejs and add the theme to the theme selection option.Then in routes->index.js render the required theme according to the user selection.

**Comment by aswinzz** [comment]
No ! you just have to integrate existing one's

**Comment by lazycipher** [comment]
@aswinzz I'm willing to work on this!

**Comment by aswinzz** [comment]
Sure
